<a href="https://colab.research.google.com/github/Rijeesha206/RIJI/blob/main/heart_disease.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.metrics import accuracy_score

In [ ]:
from google.colab  import files
files.upload()

Saving heart_disease_data.csv to heart_disease_data.csv

{'heart_disease_data.csv': b'\xef\xbb\xbfage,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target\r\n63,1,3,145,233,1,0,150,0,2.3,0,0,1,1\r\n37,1,2,130,250,0,1,187,0,3.5,0,0,2,1\r\n41,0,1,130,204,0,0,172,0,1.4,2,0,2,1\r\n56,1,1,120,236,0,1,178,0,0.8,2,0,2,1\r\n57,0,0,120,354,0,1,163,1,0.6,2,0,2,1\r\n57,1,0,140,192,0,1,148,0,0.4,1,0,1,1\r\n56,0,1,140,294,0,0,153,0,1.3,1,0,2,1\r\n44,1,1,120,263,0,1,173,0,0,2,0,3,1\r\n52,1,2,172,199,1,1,162,0,0.5,2,0,3,1\r\n57,1,2,150,168,0,1,174,0,1.6,2,0,2,1\r\n54,1,0,140,239,0,1,160,0,1.2,2,0,2,1\r\n48,0,2,130,275,0,1,139,0,0.2,2,0,2,1\r\n49,1,1,130,266,0,1,171,0,0.6,2,0,2,1\r\n64,1,3,110,211,0,0,144,1,1.8,1,0,2,1\r\n58,0,3,150,283,1,0,162,0,1,2,0,2,1\r\n50,0,2,120,219,0,1,158,0,1.6,1,0,2,1\r\n58,0,2,120,340,0,1,172,0,0,2,0,2,1\r\n66,0,3,150,226,0,1,114,0,2.6,0,0,2,1\r\n43,1,0,150,247,0,1,171,0,1.5,2,0,2,1\r\n69,0,3,140,239,0,1,151,0,1.8,2,2,2,1\r\n59,1,0,135,234,0,1,161,0,0.5,1,0,3,1\r\n44,1,2,130,233,0,1,179,1,0.4,2,0,2,1\r\n42,1,0,140,226,0,1,178,0,0,2,0,2,1\r\n61,1,2,150,243,1,1,137,1,1,1,0,2,1\r\n40,1,3,140,199,0,1,178,1,1.4,2,0,3,1\r\n71,0,1,160,302,0,1,162,0,0.4,2,2,2,1\r\n59,1,2,150,212,1,1,157,0,1.6,2,0,2,1\r\n51,1,2,110,175,0,1,123,0,0.6,2,0,2,1\r\n65,0,2,140,417,1,0,157,0,0.8,2,1,2,1\r\n53,1,2,130,197,1,0,152,0,1.2,0,0,2,1\r\n41,0,1,105,198,0,1,168,0,0,2,1,2,1\r\n65,1,0,120,177,0,1,140,0,0.4,2,0,3,1\r\n44,1,1,130,219,0,0,188,0,0,2,0,2,1\r\n54,1,2,125,273,0,0,152,0,0.5,0,1,2,1\r\n51,1,3,125,213,0,0,125,1,1.4,2,1,2,1\r\n46,0,2,142,177,0,0,160,1,1.4,0,0,2,1\r\n54,0,2,135,304,1,1,170,0,0,2,0,2,1\r\n54,1,2,150,232,0,0,165,0,1.6,2,0,3,1\r\n65,0,2,155,269,0,1,148,0,0.8,2,0,2,1\r\n65,0,2,160,360,0,0,151,0,0.8,2,0,2,1\r\n51,0,2,140,308,0,0,142,0,1.5,2,1,2,1\r\n48,1,1,130,245,0,0,180,0,0.2,1,0,2,1\r\n45,1,0,104,208,0,0,148,1,3,1,0,2,1\r\n53,0,0,130,264,0,0,143,0,0.4,1,0,2,1\r\n39,1,2,140,321,0,0,182,0,0,2,0,2,1\r\n52,1,1,120,325,0,1,172,0,0.2,2,0,2,1\r\n44,1,2,140,235,0,0,180,0,0,2,0,2,1\r\n47,1,2,138,257,0,0,156,0,0,2,0,2,1\r\n53,0,2,128,216,0,0,115,0,0,2,0,0,1\r\n53,0,0,138,234,0,0,160,0,0,2,0,2,1\r\n51,0,2,130,256,0,0,149,0,0.5,2,0,2,1\r\n66,1,0,120,302,0,0,151,0,0.4,1,0,2,1\r\n62,1,2,130,231,0,1,146,0,1.8,1,3,3,1\r\n44,0,2,108,141,0,1,175,0,0.6,1,0,2,1\r\n63,0,2,135,252,0,0,172,0,0,2,0,2,1\r\n52,1,1,134,201,0,1,158,0,0.8,2,1,2,1\r\n48,1,0,122,222,0,0,186,0,0,2,0,2,1\r\n45,1,0,115,260,0,0,185,0,0,2,0,2,1\r\n34,1,3,118,182,0,0,174,0,0,2,0,2,1\r\n57,0,0,128,303,0,0,159,0,0,2,1,2,1\r\n71,0,2,110,265,1,0,130,0,0,2,1,2,1\r\n54,1,1,108,309,0,1,156,0,0,2,0,3,1\r\n52,1,3,118,186,0,0,190,0,0,1,0,1,1\r\n41,1,1,135,203,0,1,132,0,0,1,0,1,1\r\n58,1,2,140,211,1,0,165,0,0,2,0,2,1\r\n35,0,0,138,183,0,1,182,0,1.4,2,0,2,1\r\n51,1,2,100,222,0,1,143,1,1.2,1,0,2,1\r\n45,0,1,130,234,0,0,175,0,0.6,1,0,2,1\r\n44,1,1,120,220,0,1,170,0,0,2,0,2,1\r\n62,0,0,124,209,0,1,163,0,0,2,0,2,1\r\n54,1,2,120,258,0,0,147,0,0.4,1,0,3,1\r\n51,1,2,94,227,0,1,154,1,0,2,1,3,1\r\n29,1,1,130,204,0,0,202,0,0,2,0,2,1\r\n51,1,0,140,261,0,0,186,1,0,2,0,2,1\r\n43,0,2,122,213,0,1,165,0,0.2,1,0,2,1\r\n55,0,1,135,250,0,0,161,0,1.4,1,0,2,1\r\n51,1,2,125,245,1,0,166,0,2.4,1,0,2,1\r\n59,1,1,140,221,0,1,164,1,0,2,0,2,1\r\n52,1,1,128,205,1,1,184,0,0,2,0,2,1\r\n58,1,2,105,240,0,0,154,1,0.6,1,0,3,1\r\n41,1,2,112,250,0,1,179,0,0,2,0,2,1\r\n45,1,1,128,308,0,0,170,0,0,2,0,2,1\r\n60,0,2,102,318,0,1,160,0,0,2,1,2,1\r\n52,1,3,152,298,1,1,178,0,1.2,1,0,3,1\r\n42,0,0,102,265,0,0,122,0,0.6,1,0,2,1\r\n67,0,2,115,564,0,0,160,0,1.6,1,0,3,1\r\n68,1,2,118,277,0,1,151,0,1,2,1,3,1\r\n46,1,1,101,197,1,1,156,0,0,2,0,3,1\r\n54,0,2,110,214,0,1,158,0,1.6,1,0,2,1\r\n58,0,0,100,248,0,0,122,0,1,1,0,2,1\r\n48,1,2,124,255,1,1,175,0,0,2,2,2,1\r\n57,1,0,132,207,0,1,168,1,0,2,0,3,1\r\n52,1,2,138,223,0,1,169,0,0,2,4,2,1\r\n54,0,1,132,288,1,0,159,1,0,2,1,2,1\r\n45,0,1,112,160,0,1,138,0,0,1,0,2,1\r\n53,1,0,142,226,0,0,111,1,0,2,0,3,1\r\n62,0,0,140,394,0,0,157,0,1.2,1,0,2,1\r\n52,1,0,108,233,1,1,147,0,0.1,2,3,3,1\r\n43,1,2,130,315,0,1,162,0,1.9,2,1,2,1\r\n53,1,2,130,246,1,0,173,0,0,2,3,2,1\r\n42,1,3,148,244,0,0,178,0,0.8,2,2,2,1\r\n59,1,3,178,270,0,0,145,0,4.2,0,0,3,1\r\n63,0,1,140,195,0,1,179,0,0,2,2,2,1\r\n42,1,2,120,240,1,1,194,0,0.8,0,0,3,1\r\n50,1,2,129,196,0,1,163,0,0,2,0,2,1\r\n68,0,2,120,211,0,0,115,0,1.5,1,0,2,1\r\n69,1,3,160,234,1,0,131,0,0.1,1,1,2,1\r\n45,0,0,138,236,0,0,152,1,0.2,1,0,2,1\r\n50,0,1,120,244,0,1,162,0,1.1,2,0,2,1\r\n50,0,0,110,254,0,0,159,0,0,2,0,2,1\r\n64,0,0,180,325,0,1,154,1,0,2,0,2,1\r\n57,1,2,150,126,1,1,173,0,0.2,2,1,3,1\r\n64,0,2,140,313,0,1,133,0,0.2,2,0,3,1\r\n43,1,0,110,211,0,1,161,0,0,2,0,3,1\r\n55,1,1,130,262,0,1,155,0,0,2,0,2,1\r\n37,0,2,120,215,0,1,170,0,0,2,0,2,1\r\n41,1,2,130,214,0,0,168,0,2,1,0,2,1\r\n56,1,3,120,193,0,0,162,0,1.9,1,0,3,1\r\n46,0,1,105,204,0,1,172,0,0,2,0,2,1\r\n46,0,0,138,243,0,0,152,1,0,1,0,2,1\r\n64,0,0,130,303,0,1,122,0,2,1,2,2,1\r\n59,1,0,138,271,0,0,182,0,0,2,0,2,1\r\n41,0,2,112,268,0,0,172,1,0,2,0,2,1\r\n54,0,2,108,267,0,0,167,0,0,2,0,2,1\r\n39,0,2,94,199,0,1,179,0,0,2,0,2,1\r\n34,0,1,118,210,0,1,192,0,0.7,2,0,2,1\r\n47,1,0,112,204,0,1,143,0,0.1,2,0,2,1\r\n67,0,2,152,277,0,1,172,0,0,2,1,2,1\r\n52,0,2,136,196,0,0,169,0,0.1,1,0,2,1\r\n74,0,1,120,269,0,0,121,1,0.2,2,1,2,1\r\n54,0,2,160,201,0,1,163,0,0,2,1,2,1\r\n49,0,1,134,271,0,1,162,0,0,1,0,2,1\r\n42,1,1,120,295,0,1,162,0,0,2,0,2,1\r\n41,1,1,110,235,0,1,153,0,0,2,0,2,1\r\n41,0,1,126,306,0,1,163,0,0,2,0,2,1\r\n49,0,0,130,269,0,1,163,0,0,2,0,2,1\r\n60,0,2,120,178,1,1,96,0,0,2,0,2,1\r\n62,1,1,128,208,1,0,140,0,0,2,0,2,1\r\n57,1,0,110,201,0,1,126,1,1.5,1,0,1,1\r\n64,1,0,128,263,0,1,105,1,0.2,1,1,3,1\r\n51,0,2,120,295,0,0,157,0,0.6,2,0,2,1\r\n43,1,0,115,303,0,1,181,0,1.2,1,0,2,1\r\n42,0,2,120,209,0,1,173,0,0,1,0,2,1\r\n67,0,0,106,223,0,1,142,0,0.3,2,2,2,1\r\n76,0,2,140,197,0,2,116,0,1.1,1,0,2,1\r\n70,1,1,156,245,0,0,143,0,0,2,0,2,1\r\n44,0,2,118,242,0,1,149,0,0.3,1,1,2,1\r\n60,0,3,150,240,0,1,171,0,0.9,2,0,2,1\r\n44,1,2,120,226,0,1,169,0,0,2,0,2,1\r\n42,1,2,130,180,0,1,150,0,0,2,0,2,1\r\n66,1,0,160,228,0,0,138,0,2.3,2,0,1,1\r\n71,0,0,112,149,0,1,125,0,1.6,1,0,2,1\r\n64,1,3,170,227,0,0,155,0,0.6,1,0,3,1\r\n66,0,2,146,278,0,0,152,0,0,1,1,2,1\r\n39,0,2,138,220,0,1,152,0,0,1,0,2,1\r\n58,0,0,130,197,0,1,131,0,0.6,1,0,2,1\r\n47,1,2,130,253,0,1,179,0,0,2,0,2,1\r\n35,1,1,122,192,0,1,174,0,0,2,0,2,1\r\n58,1,1,125,220,0,1,144,0,0.4,1,4,3,1\r\n56,1,1,130,221,0,0,163,0,0,2,0,3,1\r\n56,1,1,120,240,0,1,169,0,0,0,0,2,1\r\n55,0,1,132,342,0,1,166,0,1.2,2,0,2,1\r\n41,1,1,120,157,0,1,182,0,0,2,0,2,1\r\n38,1,2,138,175,0,1,173,0,0,2,4,2,1\r\n38,1,2,138,175,0,1,173,0,0,2,4,2,1\r\n67,1,0,160,286,0,0,108,1,1.5,1,3,2,0\r\n67,1,0,120,229,0,0,129,1,2.6,1,2,3,0\r\n62,0,0,140,268,0,0,160,0,3.6,0,2,2,0\r\n63,1,0,130,254,0,0,147,0,1.4,1,1,3,0\r\n53,1,0,140,203,1,0,155,1,3.1,0,0,3,0\r\n56,1,2,130,256,1,0,142,1,0.6,1,1,1,0\r\n48,1,1,110,229,0,1,168,0,1,0,0,3,0\r\n58,1,1,120,284,0,0,160,0,1.8,1,0,2,0\r\n58,1,2,132,224,0,0,173,0,3.2,2,2,3,0\r\n60,1,0,130,206,0,0,132,1,2.4,1,2,3,0\r\n40,1,0,110,167,0,0,114,1,2,1,0,3,0\r\n60,1,0,117,230,1,1,160,1,1.4,2,2,3,0\r\n64,1,2,140,335,0,1,158,0,0,2,0,2,0\r\n43,1,0,120,177,0,0,120,1,2.5,1,0,3,0\r\n57,1,0,150,276,0,0,112,1,0.6,1,1,1,0\r\n55,1,0,132,353,0,1,132,1,1.2,1,1,3,0\r\n65,0,0,150,225,0,0,114,0,1,1,3,3,0\r\n61,0,0,130,330,0,0,169,0,0,2,0,2,0\r\n58,1,2,112,230,0,0,165,0,2.5,1,1,3,0\r\n50,1,0,150,243,0,0,128,0,2.6,1,0,3,0\r\n44,1,0,112,290,0,0,153,0,0,2,1,2,0\r\n60,1,0,130,253,0,1,144,1,1.4,2,1,3,0\r\n54,1,0,124,266,0,0,109,1,2.2,1,1,3,0\r\n50,1,2,140,233,0,1,163,0,0.6,1,1,3,0\r\n41,1,0,110,172,0,0,158,0,0,2,0,3,0\r\n51,0,0,130,305,0,1,142,1,1.2,1,0,3,0\r\n58,1,0,128,216,0,0,131,1,2.2,1,3,3,0\r\n54,1,0,120,188,0,1,113,0,1.4,1,1,3,0\r\n60,1,0,145,282,0,0,142,1,2.8,1,2,3,0\r\n60,1,2,140,185,0,0,155,0,3,1,0,2,0\r\n59,1,0,170,326,0,0,140,1,3.4,0,0,3,0\r\n46,1,2,150,231,0,1,147,0,3.6,1,0,2,0\r\n67,1,0,125,254,1,1,163,0,0.2,1,2,3,0\r\n62,1,0,120,267,0,1,99,1,1.8,1,2,3,0\r\n65,1,0,110,248,0,0,158,0,0.6,2,2,1,0\r\n44,1,0,110,197,0,0,177,0,0,2,1,2,0\r\n60,1,0,125,258,0,0,141,1,2.8,1,1,3,0\r\n58,1,0,150,270,0,0,111,1,0.8,2,0,3,0\r\n68,1,2,180,274,1,0,150,1,1.6,1,0,3,0\r\n62,0,0,160,164,0,0,145,0,6.2,0,3,3,0\r\n52,1,0,128,255,0,1,161,1,0,2,1,3,0\r\n59,1,0,110,239,0,0,142,1,1.2,1,1,3,0\r\n60,0,0,150,258,0,0,157,0,2.6,1,2,3,0\r\n49,1,2,120,188,0,1,139,0,2,1,3,3,0\r\n59,1,0,140,177,0,1,162,1,0,2,1,3,0\r\n57,1,2,128,229,0,0,150,0,0.4,1,1,3,0\r\n61,1,0,120,260,0,1,140,1,3.6,1,1,3,0\r\n39,1,0,118,219,0,1,140,0,1.2,1,0,3,0\r\n61,0,0,145,307,0,0,146,1,1,1,0,3,0\r\n56,1,0,125,249,1,0,144,1,1.2,1,1,2,0\r\n43,0,0,132,341,1,0,136,1,3,1,0,3,0\r\n62,0,2,130,263,0,1,97,0,1.2,1,1,3,0\r\n63,1,0,130,330,1,0,132,1,1.8,2,3,3,0\r\n65,1,0,135,254,0,0,127,0,2.8,1,1,3,0\r\n48,1,0,130,256,1,0,150,1,0,2,2,3,0\r\n63,0,0,150,407,0,0,154,0,4,1,3,3,0\r\n55,1,0,140,217,0,1,111,1,5.6,0,0,3,0\r\n65,1,3,138,282,1,0,174,0,1.4,1,1,2,0\r\n56,0,0,200,288,1,0,133,1,4,0,2,3,0\r\n54,1,0,110,239,0,1,126,1,2.8,1,1,3,0\r\n70,1,0,145,174,0,1,125,1,2.6,0,0,3,0\r\n62,1,1,120,281,0,0,103,0,1.4,1,1,3,0\r\n35,1,0,120,198,0,1,130,1,1.6,1,0,3,0\r\n59,1,3,170,288,0,0,159,0,0.2,1,0,3,0\r\n64,1,2,125,309,0,1,131,1,1.8,1,0,3,0\r\n47,1,2,108,243,0,1,152,0,0,2,0,2,0\r\n57,1,0,165,289,1,0,124,0,1,1,3,3,0\r\n55,1,0,160,289,0,0,145,1,0.8,1,1,3,0\r\n64,1,0,120,246,0,0,96,1,2.2,0,1,2,0\r\n70,1,0,130,322,0,0,109,0,2.4,1,3,2,0\r\n51,1,0,140,299,0,1,173,1,1.6,2,0,3,0\r\n58,1,0,125,300,0,0,171,0,0,2,2,3,0\r\n60,1,0,140,293,0,0,170,0,1.2,1,2,3,0\r\n77,1,0,125,304,0,0,162,1,0,2,3,2,0\r\n35,1,0,126,282,0,0,156,1,0,2,0,3,0\r\n70,1,2,160,269,0,1,112,1,2.9,1,1,3,0\r\n59,0,0,174,249,0,1,143,1,0,1,0,2,0\r\n64,1,0,145,212,0,0,132,0,2,1,2,1,0\r\n57,1,0,152,274,0,1,88,1,1.2,1,1,3,0\r\n56,1,0,132,184,0,0,105,1,2.1,1,1,1,0\r\n48,1,0,124,274,0,0,166,0,0.5,1,0,3,0\r\n56,0,0,134,409,0,0,150,1,1.9,1,2,3,0\r\n66,1,1,160,246,0,1,120,1,0,1,3,1,0\r\n54,1,1,192,283,0,0,195,0,0,2,1,3,0\r\n69,1,2,140,254,0,0,146,0,2,1,3,3,0\r\n51,1,0,140,298,0,1,122,1,4.2,1,3,3,0\r\n43,1,0,132,247,1,0,143,1,0.1,1,4,3,0\r\n62,0,0,138,294,1,1,106,0,1.9,1,3,2,0\r\n67,1,0,100,299,0,0,125,1,0.9,1,2,2,0\r\n59,1,3,160,273,0,0,125,0,0,2,0,2,0\r\n45,1,0,142,309,0,0,147,1,0,1,3,3,0\r\n58,1,0,128,259,0,0,130,1,3,1,2,3,0\r\n50,1,0,144,200,0,0,126,1,0.9,1,0,3,0\r\n62,0,0,150,244,0,1,154,1,1.4,1,0,2,0\r\n38,1,3,120,231,0,1,182,1,3.8,1,0,3,0\r\n66,0,0,178,228,1,1,165,1,1,1,2,3,0\r\n52,1,0,112,230,0,1,160,0,0,2,1,2,0\r\n53,1,0,123,282,0,1,95,1,2,1,2,3,0\r\n63,0,0,108,269,0,1,169,1,1.8,1,2,2,0\r\n54,1,0,110,206,0,0,108,1,0,1,1,2,0\r\n66,1,0,112,212,0,0,132,1,0.1,2,1,2,0\r\n55,0,0,180,327,0,2,117,1,3.4,1,0,2,0\r\n49,1,2,118,149,0,0,126,0,0.8,2,3,2,0\r\n54,1,0,122,286,0,0,116,1,3.2,1,2,2,0\r\n56,1,0,130,283,1,0,103,1,1.6,0,0,3,0\r\n46,1,0,120,249,0,0,144,0,0.8,2,0,3,0\r\n61,1,3,134,234,0,1,145,0,2.6,1,2,2,0\r\n67,1,0,120,237,0,1,71,0,1,1,0,2,0\r\n58,1,0,100,234,0,1,156,0,0.1,2,1,3,0\r\n47,1,0,110,275,0,0,118,1,1,1,1,2,0\r\n52,1,0,125,212,0,1,168,0,1,2,2,3,0\r\n58,1,0,146,218,0,1,105,0,2,1,1,3,0\r\n57,1,1,124,261,0,1,141,0,0.3,2,0,3,0\r\n58,0,1,136,319,1,0,152,0,0,2,2,2,0\r\n61,1,0,138,166,0,0,125,1,3.6,1,1,2,0\r\n42,1,0,136,315,0,1,125,1,1.8,1,0,1,0\r\n52,1,0,128,204,1,1,156,1,1,1,0,0,0\r\n59,1,2,126,218,1,1,134,0,2.2,1,1,1,0\r\n40,1,0,152,223,0,1,181,0,0,2,0,3,0\r\n61,1,0,140,207,0,0,138,1,1.9,2,1,3,0\r\n46,1,0,140,311,0,1,120,1,1.8,1,2,3,0\r\n59,1,3,134,204,0,1,162,0,0.8,2,2,2,0\r\n57,1,1,154,232,0,0,164,0,0,2,1,2,0\r\n57,1,0,110,335,0,1,143,1,3,1,1,3,0\r\n55,0,0,128,205,0,2,130,1,2,1,1,3,0\r\n61,1,0,148,203,0,1,161,0,0,2,1,3,0\r\n58,1,0,114,318,0,2,140,0,4.4,0,3,1,0\r\n58,0,0,170,225,1,0,146,1,2.8,1,2,1,0\r\n67,1,2,152,212,0,0,150,0,0.8,1,0,3,0\r\n44,1,0,120,169,0,1,144,1,2.8,0,0,1,0\r\n63,1,0,140,187,0,0,144,1,4,2,2,3,0\r\n63,0,0,124,197,0,1,136,1,0,1,0,2,0\r\n59,1,0,164,176,1,0,90,0,1,1,2,1,0\r\n57,0,0,140,241,0,1,123,1,0.2,1,0,3,0\r\n45,1,3,110,264,0,1,132,0,1.2,1,0,3,0\r\n68,1,0,144,193,1,1,141,0,3.4,1,2,3,0\r\n57,1,0,130,131,0,1,115,1,1.2,1,1,3,0\r\n57,0,1,130,236,0,0,174,0,0,1,1,2,0\r\n'}

In [ ]:
# loading the data from csv file to a Pandas DataFrame
heart_data = pd.read_csv('heart_disease_data.csv')

In [ ]:
heart_data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [ ]:
heart_data.shape

(303, 14)

In [ ]:
heart_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [ ]:
heart_data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [ ]:
heart_data.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [ ]:
heart_data['target'].value_counts()

1    165
0    138
Name: target, dtype: int64

In [ ]:
heart_data.groupby('target').mean()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
target,,,,,,,,,,,,,
0,56.601449,0.826087,0.478261,134.398551,251.086957,0.159420,0.449275,139.101449,0.550725,1.585507,1.166667,1.166667,2.543478
1,52.496970,0.563636,1.375758,129.303030,242.230303,0.139394,0.593939,158.466667,0.139394,0.583030,1.593939,0.363636,2.121212

In [ ]:
X = heart_data.drop(columns=['target'], axis=1)
Y = heart_data['target']

In [ ]:
print(X)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3
1     37    1   2       130   250    0        1      187      0      3.5
2     41    0   1       130   204    0        0      172      0      1.4
3     56    1   1       120   236    0        1      178      0      0.8
4     57    0   0       120   354    0        1      163      1      0.6
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
298   57    0   0       140   241    0        1      123      1      0.2
299   45    1   3       110   264    0        1      132      0      1.2
300   68    1   0       144   193    1        1      141      0      3.4
301   57    1   0       130   131    0        1      115      1      1.2
302   57    0   1       130   236    0        0      174      0      0.0

     slope  ca  thal
0        0   0     1
1        0   0     2
2        2   0     2
3        2   0     2
4        2   0     2
..     ...  ..   ...
298      1   0     3
299      1   0     3
300      1   2     3
301      1   1     3
302      1   1     2

[303 rows x 13 columns]

In [ ]:
print(Y)

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

In [ ]:
print(X.shape, X_train.shape, X_test.shape)

(303, 13) (242, 13) (61, 13)

In [ ]:
scaler = StandardScaler()

In [ ]:
scaler.fit(X_train)

StandardScaler()

In [ ]:
X_train = scaler.transform(X_train)

In [ ]:
X_test = scaler.transform(X_test)

In [ ]:
print(X_train)

[[ 0.55722251  0.68964466 -0.94111333 ... -0.67505958  1.31483593
   1.14497234]
 [ 1.54391408  0.68964466  1.95400648 ... -0.67505958  0.29825352
  -0.47539787]
 [-0.10057187  0.68964466 -0.94111333 ...  0.9585846  -0.71832889
  -0.47539787]
 ...
 [-2.84138178  0.68964466  0.02392661 ...  0.9585846  -0.71832889
  -0.47539787]
 [-0.53910145 -1.4500221   0.98896655 ... -0.67505958 -0.71832889
  -0.47539787]
 [ 0.8861197   0.68964466 -0.94111333 ... -0.67505958  0.29825352
   1.14497234]]

In [ ]:
model = svm.SVC(kernel='linear')

In [ ]:
model.fit(X_train, Y_train)

SVC(kernel='linear')

In [ ]:
# accuracy score on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(Y_train, X_train_prediction)

In [ ]:
print('Accuracy score of training data : ', training_data_accuracy)

Accuracy score of training data :  0.8429752066115702

In [ ]:
# accuracy score on training data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(Y_test, X_test_prediction)

In [ ]:
print('Accuracy score of test data : ', test_data_accuracy)

Accuracy score of test data :  0.8688524590163934

In [ ]:
input_data = (62,0,0,140,268,0,0,160,0,3.6,0,2,2)

# change the input data to a numpy array
input_data_as_numpy_array= np.asarray(input_data)

# reshape the numpy array as we are predicting for only on instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = model.predict(input_data_reshaped)
print(prediction)

if (prediction[0]== 0):
  print('The Person does not have a Heart Disease')
else:
  print('The Person has Heart Disease')

[0]
The Person does not have a Heart Disease